# Generated by Django 5.0.8 on 2024-08-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='library',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
